CREATE DATABASE QLCuaHang
GO

USE QLCuaHang
GO

--DATETIME
SET DATEFORMAT DMY

--**TABLE
CREATE TABLE NHANVIEN (
    MaNV VARCHAR(10) PRIMARY KEY,
    TenNV VARCHAR(50),
    GioiTinh VARCHAR(3),
    NgaySinh DATE,
    DiaChi VARCHAR(50),
    SDT VARCHAR(10)
);

CREATE TABLE KHACHHANG (
    MaKH VARCHAR(10) PRIMARY KEY,
    TenKH VARCHAR(50),
    DiaChi VARCHAR(50),
    SDT VARCHAR(10)
);

CREATE TABLE HOADON (
    MaHD VARCHAR(10) PRIMARY KEY,
    MaKH VARCHAR(10) REFERENCES KHACHHANG(MaKH),
    MaNV VARCHAR(10) REFERENCES NHANVIEN(MaNV),
    NgayLapHD DATE
);

CREATE TABLE SANPHAM (
    MaSP VARCHAR(10) PRIMARY KEY,
    TenSP VARCHAR(50),
    DonViTinh VARCHAR(10),
    DonGia INT
);

CREATE TABLE CHITIETHD (
    MaHD VARCHAR(10),
    MaSP VARCHAR(10),
    SoLuong INT,
    PRIMARY KEY (MaHD, MaSP),
    FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD),
    FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP)
);

--STORES
-------------------------------------------------------------------------------------------------
--NHAN VIEN
CREATE PROC READ_NV
AS
SELECT * FROM NHANVIEN;
GO

CREATE PROC INSERT_NV @MaNV VARCHAR(10), @TenNV VARCHAR(50), @GioiTinh VARCHAR(3), @NgaySinh DATE, @DiaChi VARCHAR(50), @SDT VARCHAR(10)
AS
BEGIN
	INSERT INTO NHANVIEN
	VALUES(@MaNV, @TenNV, @GioiTinh, @NgaySinh, @DiaChi, @SDT);
END
GO

CREATE PROC UPDATE_NV @MaNV VARCHAR(10), @TenNV VARCHAR(50), @GioiTinh VARCHAR(3), @NgaySinh DATE, @DiaChi VARCHAR(50), @SDT VARCHAR(10)
AS
BEGIN
	UPDATE NHANVIEN
	SET TenNV= @TenNV, GioiTinh= @GioiTinh, NgaySinh= @NgaySinh, DiaChi= @DiaChi, SDT= @SDT
	WHERE MaNV=@MaNV;
END
GO

CREATE PROC DELETE_NV @MaNV VARCHAR(10)
AS
BEGIN
	DELETE FROM NHANVIEN
	WHERE MaNV=@MaNV;
END
GO

CREATE PROC SEARCH_NV @Key VARCHAR(50)
AS
BEGIN
	SELECT * FROM NHANVIEN
	WHERE MaNV=@Key OR TenNV LIKE '%'+@Key+'%';
END
GO

EXEC INSERT_NV '1', 'NV1', 'NAM', '12/01/2000', 'HCM 1', '0342546541';
EXEC INSERT_NV '2', 'NV2', 'NAM', '12/02/2000', 'HCM 2', '2413423';
EXEC INSERT_NV '3', 'NV3', 'NU', '12/03/2000', 'HCM 3', '5123413';
EXEC INSERT_NV '4', 'NV4', 'NAM', '12/04/2000', 'HCM 4', '21412341432';
EXEC INSERT_NV '5', 'NV5', 'NU', '12/05/2000', 'HCM 5', '2341234';
-------------------------------------------------------------------------------------------------
